
import PDFDocument from 'pdfkit';
import { AIService } from './ai';

const aiService = new AIService();

export const generatePDFReport = async (profileA: any, profileB: any, res: any) => {
    // 1. Get AI Content
    const reportText = await aiService.generateDeepAnalysis(profileA, profileB);

    // 2. Setup PDF Stream
    const doc = new PDFDocument({ margin: 50 });

    // Pipe to response
    doc.pipe(res);

    // 3. Header
    doc.fontSize(25).font('Helvetica-Bold').text('LifePartner.AI', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Premium Compatibility Audit', { align: 'center' });
    doc.moveDown();
    doc.lineWidth(2).moveTo(50, 100).lineTo(550, 100).stroke();
    doc.moveDown(2);

    // 4. Profiles Intro
    doc.fontSize(14).font('Helvetica-Bold').text(`Analysis for:`, { underline: true });
    doc.fontSize(12).font('Helvetica')
        .text(`• ${profileA.full_name || 'Partner A'} (${profileA.age || '?'})`)
        .text(`• ${profileB.full_name || 'Partner B'} (${profileB.age || '?'})`);

    doc.moveDown(2);

    // 5. Render Markdown-ish Content
    const lines = reportText.split('\n');

    lines.forEach(line => {
        const trimmed = line.trim();
        if (trimmed.startsWith('# ')) {
            // H1
            doc.moveDown();
            doc.fontSize(18).font('Helvetica-Bold').fillColor('#2563EB').text(trimmed.replace('# ', ''));
            doc.fillColor('black').font('Helvetica').fontSize(12).moveDown(0.5);
        } else if (trimmed.startsWith('## ')) {
            // H2
            doc.moveDown();
            doc.fontSize(15).font('Helvetica-Bold').fillColor('#4B5563').text(trimmed.replace('## ', ''));
            doc.fillColor('black').font('Helvetica').fontSize(12).moveDown(0.5);
        } else if (trimmed.length > 0) {
            // Body
            doc.text(trimmed, { align: 'justify' });
            doc.moveDown(0.5);
        }
    });

    // Footer
    doc.fontSize(10).fillColor('grey').text('Generated by LifePartner.AI True Intelligence Engine', 50, 700, { align: 'center' });

    doc.end();
};
