'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'es' | 'hi' | 'te' | 'ta' | 'fr' | 'de' | 'ar' | 'zh' | 'ja' | 'ko' | 'pt' | 'th' | 'ms' | 'id' | 'ru';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  dir?: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🌐', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷', dir: 'ltr' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭', dir: 'ltr' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾', dir: 'ltr' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩', dir: 'ltr' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', dir: 'ltr' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', dir: 'ltr' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇦🇪', dir: 'rtl' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷', dir: 'ltr' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    heroDatingPill: 'Worldwide Dating Mode',
    heroMatrimonyPill: 'Serious Matrimony Mode',
    heroTitlePrefix: 'Connect & Chat',
    heroTitleGradient: 'Free Worldwide.',
    heroSub: 'The world\'s #1 AI platform built for both Worldwide Dating & Serious Matrimony. Instant direct chat, verified profiles, zero forced subscriptions.',
    quickSearchTitle: 'Quick Match Search',
    iAmA: 'I am a',
    lookingFor: 'Looking for',
    goal: 'Goal',
    location: 'Location',
    findMatchesBtn: 'Find Matches Free',
    trust100Free: '100% Free Direct Chat',
    trustVerified: 'Verified Human Profiles',
    trustGlobal: 'Global & NRI Reach',
    navFeatures: 'App Features',
    navStories: 'Stories & Snaps',
    navMusic: 'Music Match',
    navWorkflow: 'How It Works',
    navBlog: 'Blog',
    navCommunity: 'Community',
    navLogin: 'Log In',
    navGetStarted: 'Get Started Free',
    snapTitle: 'Instant Snaps',
    snapDesc: 'Share quick photo moments that disappear after viewing. Pure authentic vibes with zero filter pressure & screenshot protection.',
    storiesTitle: '24-Hour Stories Feed',
    storiesDesc: 'Express your daily life through photo & video stories. Reply directly to any story to start a natural conversation instantly.',
    musicTitle: 'Music Vibe Matching',
    musicDesc: 'Sync your Spotify anthems & listen to favorite songs together in live chat. Music brings soulmates together effortlessly.',
    connectTitle: 'How Life Partners Connect Worldwide',
    connectSub: 'From smart AI discovery to real-life marriage, here is how our global platform makes finding your soulmate simple & safe.',
    step1Title: '1. AI Smart & Cosmic Match',
    step1Desc: 'Our AI analyzes deep compatibility, values, NRI preferences, and astrology to introduce your highest quality matches.',
    step2Title: '2. Snaps, Stories & Music Vibe',
    step2Desc: 'Explore real authentic daily snaps, 24-hour stories, and shared music anthems to know their real personality.',
    step3Title: '3. 100% Free Instant Direct Chat',
    step3Desc: 'Start instant messaging, voice note exchange, and crystal-clear HD video calls without paywalls or hidden fees.',
    step4Title: '4. Safe Meetups & Life Partner Journey',
    step4Desc: 'Connect at verified local meetups or start your journey to wedding matrimony with verified safe identity protection.',
  },
  es: {
    heroDatingPill: 'Modo Citas Mundiales',
    heroMatrimonyPill: 'Modo Matrimonio Serio',
    heroTitlePrefix: 'Conéctate y Chatea',
    heroTitleGradient: 'Gratis en todo el mundo.',
    heroSub: 'La plataforma de IA número 1 del mundo para citas internacionales y matrimonio serio. Chat directo instantáneo, perfiles verificados y cero suscripciones.',
    quickSearchTitle: 'Búsqueda Rápida de Pareja',
    iAmA: 'Soy un/a',
    lookingFor: 'Busco',
    goal: 'Objetivo',
    location: 'Ubicación',
    findMatchesBtn: 'Buscar Parejas Gratis',
    trust100Free: 'Chat Directo 100% Gratis',
    trustVerified: 'Perfiles Humanos Verificados',
    trustGlobal: 'Alcance Global e Internacional',
    navFeatures: 'Características',
    navStories: 'Historias y Snaps',
    navMusic: 'Música Vibe',
    navWorkflow: 'Cómo Funciona',
    navBlog: 'Blog',
    navCommunity: 'Comunidad',
    navLogin: 'Iniciar Sesión',
    navGetStarted: 'Empezar Gratis',
    snapTitle: 'Snaps Instantáneos',
    snapDesc: 'Comparte momentos fotográficos rápidos que desaparecen tras verse. Momentos auténticos sin presión de filtros.',
    storiesTitle: 'Historias de 24 Horas',
    storiesDesc: 'Expresa tu día a día con historias de fotos y videos. Responde directamente a cualquier historia para romper el hielo.',
    musicTitle: 'Emparejamiento por Música',
    musicDesc: 'Sincroniza tus canciones favoritas de Spotify y escúchalas en chat en vivo. La música conecta almas gemelas.',
    connectTitle: 'Cómo se Conectan las Parejas en Todo el Mundo',
    connectSub: 'Desde el descubrimiento con IA hasta el matrimonio real, así es como nuestra plataforma conecta parejas de forma segura.',
    step1Title: '1. Coincidencia IA y Cósmica',
    step1Desc: 'Nuestra IA analiza compatibilidad profunda, valores y preferencias para sugerirte las mejores parejas.',
    step2Title: '2. Snaps, Historias y Música',
    step2Desc: 'Explora snaps diarios, historias de 24h y gustos musicales para conocer su personalidad real.',
    step3Title: '3. Chat Directo 100% Gratis',
    step3Desc: 'Inicia chats, notas de voz y videollamadas HD al instante sin muros de pago ni tarifas ocultas.',
    step4Title: '4. Citas Seguras y Matrimonio',
    step4Desc: 'Conéctate en eventos locales verificados o inicia tu camino hacia el matrimonio con protección total de identidad.',
  },
  hi: {
    heroDatingPill: 'वर्ल्डवाइड डेटिंग मोड',
    heroMatrimonyPill: 'सीरियस मैरिज मोड',
    heroTitlePrefix: 'जुड़ें और चैट करें',
    heroTitleGradient: 'दुनिया भर में 100% मुफ्त।',
    heroSub: 'दुनिया की #1 AI डेटिंग और मैट्रिमोनी ऐप। तुरंत डायरेक्ट चैट, वेरीफाइड प्रोफाइल और जीरो फीस।',
    quickSearchTitle: 'क्विक मैच सर्च',
    iAmA: 'मैं हूँ',
    lookingFor: 'तलाश है',
    goal: 'लक्ष्य',
    location: 'स्थान',
    findMatchesBtn: 'फ्री मैच खोजें',
    trust100Free: '100% फ्री डायरेक्ट चैट',
    trustVerified: 'वेरीफाइड असली प्रोफाइल',
    trustGlobal: 'ग्लोबल और एनआरआई रीच',
    navFeatures: 'फीचर्स',
    navStories: 'स्टोरीज़ और स्नैप्स',
    navMusic: 'म्यूजिक वाइब',
    navWorkflow: 'यह कैसे काम करता है',
    navBlog: 'ब्लॉग',
    navCommunity: 'कम्युनिटी',
    navLogin: 'लॉग इन',
    navGetStarted: 'फ्री शुरू करें',
    snapTitle: 'इन्स्टेंट स्नैप्स',
    snapDesc: 'देखने के बाद गायब होने वाले स्नैप्स शेयर करें। बिना किसी फिल्टर दबाव के असली रूप दिखाएं।',
    storiesTitle: '24-घंटे स्टोरीज़ फ़ीड',
    storiesDesc: 'फोटो और वीडियो स्टोरीज़ से अपना दैनिक जीवन शेयर करें और तुरंत बातचीत शुरू करें।',
    musicTitle: 'म्यूजिक वाइब मैचिंग',
    musicDesc: 'अपने पसंदीदा गानों को सिंक करें और चैट में एक साथ सुनें। संगीत से लाइफ पार्टनर आसानी से जुड़ते हैं।',
    connectTitle: 'लाइफ पार्टनर आसानी से कैसे जुड़ते हैं',
    connectSub: 'स्मार्ट AI सर्च से लेकर शादी तक, जानें कि दुनिया भर में लाइफ पार्टनर कैसे आसानी से कनेक्ट होते हैं।',
    step1Title: '1. AI स्मार्ट और कॉस्मिक मैच',
    step1Desc: 'हमारी AI आपकी पसंद, कुंडली और प्राथमिकताओं का विश्लेषण करके सबसे बेहतरीन मैच दिखाती है।',
    step2Title: '2. स्नैप्स, स्टोरीज़ और म्यूजिक',
    step2Desc: 'सामने वाले की असली पर्सनालिटी जानने के लिए उनके स्नैप्स, स्टोरीज़ और गानों की लिस्ट देखें।',
    step3Title: '3. 100% फ्री तुरंत डायरेक्ट चैट',
    step3Desc: 'बिना किसी पेमेंट के तुरंत मैसेज, वॉइस नोट्स और HD वीडियो कॉल पर बात करें।',
    step4Title: '4. सुरक्षित मुलाकात और विवाह सफर',
    step4Desc: 'वेरीफाइड मुलाकात इवेंट्स में मिलें या पूरी सुरक्षा के साथ अपने शादी के सफर की शुरुआत करें।',
  },
  te: {
    heroDatingPill: 'వరల్డ్ వైడ్ డేటింగ్ మోడ్',
    heroMatrimonyPill: 'సీరియస్ మ్యాట్రిమోనీ మోడ్',
    heroTitlePrefix: 'కనెక్ట్ అవ్వండి & చాట్ చేయండి',
    heroTitleGradient: 'ప్రపంచమంతటా 100% ఫ్రీ.',
    heroSub: 'ప్రపంచంలోనే #1 AI డేటింగ్ & మ్యాట్రిమోనీ ప్లాట్‌ఫాం. డైరెక్ట్ చాట్, వెరిఫైడ్ ప్రొఫైల్స్, జీరో పేవాల్స్.',
    quickSearchTitle: 'క్విక్ మ్యాచ్ సెర్చ్',
    iAmA: 'నేను',
    lookingFor: 'కోరుకుంటున్నది',
    goal: 'లక్ష్యం',
    location: 'ప్రాంతం',
    findMatchesBtn: 'ఉచితంగా మ్యాచ్ చూడండి',
    trust100Free: '100% ఫ్రీ డైరెక్ట్ చాట్',
    trustVerified: 'వెరిఫైడ్ ప్రొఫైల్స్',
    trustGlobal: 'గ్లోబల్ & NRI రీచ్',
    navFeatures: 'ఫీచర్లు',
    navStories: 'స్టోరీస్ & స్నాప్స్',
    navMusic: 'మ్యూజిక్ వైబ్',
    navWorkflow: 'ఎలా పనిచేస్తుంది',
    navBlog: 'బ్లాగ్',
    navCommunity: 'కమ్యూనిటీ',
    navLogin: 'లాగిన్',
    navGetStarted: 'ఉచితంగా ప్రారంభించండి',
    snapTitle: 'ఇన్స్టంట్ స్నాప్స్',
    snapDesc: 'చూసిన తర్వాత మాయమయ్యే స్నాప్స్ షేర్ చేయండి. ఎటువంటి ఫిల్టర్స్ లేకుండా ఒరిజినల్ ప్రొఫైల్స్ చూసే సౌకర్యం.',
    storiesTitle: '24 గంటల స్టోరీస్ ఫీడ్',
    storiesDesc: 'మీ డైలీ లైఫ్ మొమెంట్స్‌ను ఫోటోలు & వీడియోల ద్వారా షేర్ చేయండి మరియు సులభంగా చాట్ ప్రారంభించండి.',
    musicTitle: 'మ్యూజిక్ వైబ్ మ్యాచింగ్',
    musicDesc: 'మీకు ఇష్టమైన స్పాటిఫై పాటలను సింక్ చేయండి. సంగీతంతో లైఫ్ పార్ట్‌నర్స్‌ను సులభంగా కనుగొనవచ్చు.',
    connectTitle: 'లైఫ్ పార్టనర్స్ సులభంగా ఎలా కనెక్ట్ అవుతారు',
    connectSub: 'స్మార్ట్ AI మ్యాచ్ నుండి నిజ జీవిత వివాహం వరకు, ప్రపంచమంతటా సోల్‌మేట్స్‌ను కలుసుకోవడం చాలా సులభం.',
    step1Title: '1. AI స్మార్ట్ & కాస్మిక్ మ్యాచ్',
    step1Desc: 'మీ అభిరుచులు, కుండలి & NRI ప్రాధాన్యతలను AI విశ్లేషించి సరైన మ్యాచ్‌లను చూపిస్తుంది.',
    step2Title: '2. స్నాప్స్, స్టోరీస్ & మ్యూజిక్',
    step2Desc: 'వారి నిజమైన వ్యక్తిత్వాన్ని తెలుసుకోవడానికి రోజువారీ స్నాప్స్, స్టోరీస్ & మ్యూజిక్ అభిరుచులను చూడండి.',
    step3Title: '3. 100% ఫ్రీ డైరెక్ట్ చాట్',
    step3Desc: 'ఎలాంటి చెల్లింపులు లేకుండా తక్షణ మెసేజింగ్, వాయిస్ నోట్స్ & HD వీడియో కాల్స్ చేయండి.',
    step4Title: '4. సేఫ్ మీటప్స్ & పెళ్లి ప్రయాణం',
    step4Desc: 'వెరిఫైడ్ లోకల్ మీటప్స్‌లో కలవండి లేదా పూర్తి రక్షణతో మీ వివాహ ప్రయాణాన్ని ప్రారంభించండి.',
  },
  ta: {
    heroDatingPill: 'உலகளாவிய டேட்டிங்',
    heroMatrimonyPill: 'திருமண மேட்ரிமோனி',
    heroTitlePrefix: 'இணையுங்கள் & பேசுங்கள்',
    heroTitleGradient: 'உலகளவில் 100% இலவசம்.',
    heroSub: 'உலகின் முதன்மை AI டேட்டிங் மற்றும் மேட்ரிமோனி ஆப். உடனடி சாட், சரிபார்க்கப்பட்ட சுயவிவரங்கள்.',
    quickSearchTitle: 'விரைவு மேட்ச் தேடல்',
    iAmA: 'நான்',
    lookingFor: 'தேடுவது',
    goal: 'இலக்கு',
    location: 'இடம்',
    findMatchesBtn: 'இலவசமாக தேடுங்கள்',
    trust100Free: '100% இலவச நேரிடை சாட்',
    trustVerified: 'சரிபார்க்கப்பட்ட மனிதர்கள்',
    trustGlobal: 'சர்வதேச மற்றும் NRI அணுகல்',
    navFeatures: 'அம்சங்கள்',
    navStories: 'ஸ்டோரிகள் & ஸ்னாப்ஸ்',
    navMusic: 'இசை வைப்',
    navWorkflow: 'செயல்முறை',
    navBlog: 'வலைப்பதிவு',
    navCommunity: 'சமூகம்',
    navLogin: 'உள்நுழைக',
    navGetStarted: 'இலவசமாக தொடங்கவும்',
    snapTitle: 'உடனடி ஸ்னாப்ஸ்',
    snapDesc: 'பார்த்த பின் மறையும் புகைப்படங்களை பகிர்ந்து உண்மையான உணர்வுகளை வெளிப்படுத்துங்கள்.',
    storiesTitle: '24 மணிநேர ஸ்டோரிகள்',
    storiesDesc: 'உங்கள் அன்றாட வாழ்க்கையை புகைப்படங்கள் மற்றும் வீடியோக்கள் மூலம் பகிர்ந்து எளிதாக உரையாடுங்கள்.',
    musicTitle: 'இசை பொருத்தம்',
    musicDesc: 'பிடித்த பாடல்களை இணைத்து சாட்டில் ஒன்றாக கேளுங்கள். இசை மூலம் வாழ்க்கைத்துணையை கண்டறியுங்கள்.',
    connectTitle: 'வாழ்க்கைத்துணை எவ்வாறு எளிதாக இணைகிறார்கள்',
    connectSub: 'செயற்கை நுண்ணறிவு தேடலில் இருந்து திருமணம் வரை எளிதான மற்றும் பாதுகாப்பான இணைப்பு.',
    step1Title: '1. AI மற்றும் ஜோதிட பொருத்தம்',
    step1Desc: 'உங்கள் விருப்பங்கள் மற்றும் ஜாதகத்தை பகுப்பாய்வு செய்து சிறந்த பொருத்தங்களை AI கண்டறியும்.',
    step2Title: '2. ஸ்னாப்ஸ், ஸ்டோரிகள் & இசை',
    step2Desc: 'அவர்களின் உண்மையான குணநலன்களை அறிந்துகொள்ள அவர்களின் ஸ்டோரிகள் மற்றும் இசையை பாருங்கள்.',
    step3Title: '3. 100% இலவச நேரடி சாட்',
    step3Desc: 'எந்த கட்டணமும் இன்றி செய்தி, குரல் குறிப்புகள் மற்றும் HD வீடியோ அழைப்புகளை பயன்படுத்துங்கள்.',
    step4Title: '4. பாதுகாப்பான சந்திப்பு & திருமணம்',
    step4Desc: 'பாதுகாப்பான சந்திப்புகளில் பங்கேற்று உங்கள் திருமண பயணத்தை நம்பிக்கையுடன் தொடங்குங்கள்.',
  },
  fr: {
    heroDatingPill: 'Mode Rencontres Mondiales',
    heroMatrimonyPill: 'Mode Mariage Sérieux',
    heroTitlePrefix: 'Connectez-vous et Discutez',
    heroTitleGradient: 'Gratuit dans le monde entier.',
    heroSub: 'La 1ère plateforme IA au monde pour les rencontres et le mariage sérieux. Chat direct instantané, profils vérifiés, zéro abonnement.',
    quickSearchTitle: 'Recherche Rapide de Profils',
    iAmA: 'Je suis un/une',
    lookingFor: 'Je cherche',
    goal: 'Objectif',
    location: 'Localisation',
    findMatchesBtn: 'Trouver des Profils Gratuits',
    trust100Free: 'Chat Direct 100% Gratuit',
    trustVerified: 'Profils Humains Vérifiés',
    trustGlobal: 'Portée Mondiale et Internationale',
    navFeatures: 'Fonctionnalités',
    navStories: 'Stories et Snaps',
    navMusic: 'Musique Vibe',
    navWorkflow: 'Comment ça marche',
    navBlog: 'Blog',
    navCommunity: 'Communauté',
    navLogin: 'Connexion',
    navGetStarted: 'Commencer Gratuitement',
    snapTitle: 'Snaps Instantanés',
    snapDesc: 'Partagez des photos éphémères qui disparaissent après lecture. Une authenticité pure sans pression.',
    storiesTitle: 'Feed Stories 24h',
    storiesDesc: 'Exprimez votre quotidien avec des stories photo & vidéo. Répondez directement pour lancer la discussion.',
    musicTitle: 'Compatibilité Musicale',
    musicDesc: 'Synchrosisez vos titres préférés Spotify et écoutez la musique ensemble en direct.',
    connectTitle: 'Comment les Partenaires de Vie se Connectent',
    connectSub: 'De la recherche intelligente par IA jusqu au mariage réel, trouvez votre âme sœur simplement et en toute sécurité.',
    step1Title: '1. Match IA et Cosmique',
    step1Desc: 'L IA analyse votre compatibilité, vos valeurs et vos critères pour sélectionner vos meilleurs profils.',
    step2Title: '2. Snaps, Stories & Musique',
    step2Desc: 'Découvrez leurs snaps, stories 24h et goûts meuzicaux pour percevoir leur vraie personnalité.',
    step3Title: '3. Chat Direct 100% Gratuit',
    step3Desc: 'Discutez, envoyez des messages vocaux et passez des appels vidéo HD sans aucun frais caché.',
    step4Title: '4. Rencontres et Mariage Sécurisé',
    step4Desc: 'Rencontrez-vous lors d événements locaux vérifiés et démarrez votre vie à deux en toute quiétude.',
  },
  de: {
    heroDatingPill: 'Weltweiter Dating-Modus',
    heroMatrimonyPill: 'Ernster Heirats-Modus',
    heroTitlePrefix: 'Verbinden & Chatten',
    heroTitleGradient: 'Weltweit 100% Kostenlos.',
    heroSub: 'Die führende KI-Plattform für weltweites Dating & ernsthafte Partnersuche. Direktchat, verifizierte Profile, keine Abogebühren.',
    quickSearchTitle: 'Schnellsuche nach Partnern',
    iAmA: 'Ich bin',
    lookingFor: 'Suche nach',
    goal: 'Ziel',
    location: 'Standort',
    findMatchesBtn: 'Kostenlos Partner Finden',
    trust100Free: '100% Kostenloser Direktchat',
    trustVerified: 'Verifizierte Profile',
    trustGlobal: 'Weltweite Reichweite',
    navFeatures: 'Funktionen',
    navStories: 'Stories & Snaps',
    navMusic: 'Musik Match',
    navWorkflow: 'So funktioniert es',
    navBlog: 'Blog',
    navCommunity: 'Community',
    navLogin: 'Anmelden',
    navGetStarted: 'Kostenlos Starten',
    snapTitle: 'Sofort-Snaps',
    snapDesc: 'Teile Fotos, die nach dem Anschauen verschwinden. Echte Einblicke ohne Filterdruck.',
    storiesTitle: '24-Stunden-Stories',
    storiesDesc: 'Teile dein Leben in Stories und antworte direkt, um ungezwungen ins Gespräch zu kommen.',
    musicTitle: 'Musik-Passung',
    musicDesc: 'Synchronisiere deine Lieblingssongs und höre gemeinsam Musik im Chat.',
    connectTitle: 'Wie Lebenspartner Weltweit Zusammenfinden',
    connectSub: 'Von KI-Matching bis zur echten Hochzeit: So einfach und sicher finden Paare zueinander.',
    step1Title: '1. KI & Kosmisches Matching',
    step1Desc: 'Unsere KI analysiert Persönlichkeit, Werte und Wünsche für beste Partnerangebote.',
    step2Title: '2. Snaps, Stories & Musik',
    step2Desc: 'Lerne den echten Charakter durch tägliche Snaps, Stories und Musikgeschmack kennen.',
    step3Title: '3. 100% Kostenloser Direktchat',
    step3Desc: 'Starte sofortige Nachrichten, Sprachnachrichten & HD-Videoanrufe ohne Bezahlschranken.',
    step4Title: '4. Sichere Treffen & Eheweg',
    step4Desc: 'Triff dich bei geprüften Events oder starte deine Hochzeitsreise mit voller Identitätssicherheit.',
  },
  ar: {
    heroDatingPill: 'وضع التعارف العالمي',
    heroMatrimonyPill: 'وضع الزواج الجاد',
    heroTitlePrefix: 'تواصل ودردش',
    heroTitleGradient: 'مجاناً حول العالم.',
    heroSub: 'منصة الذكاء الاصطناعي الأولى عالمياً للتعارف والزواج الجاد. دردشة مباشرة، بروفايلات موثقة بدون اشتراكات.',
    quickSearchTitle: 'بحث سريع عن شريك',
    iAmA: 'أنا',
    lookingFor: 'أبحث عن',
    goal: 'الهدف',
    location: 'الموقع',
    findMatchesBtn: 'ابحث عن مطابقات مجاناً',
    trust100Free: 'دردشة مباشرة مجانية 100%',
    trustVerified: 'ملفات شخصية موثقة',
    trustGlobal: 'وصول عالمي ودولي',
    navFeatures: 'المميزات',
    navStories: 'القصص واللقطات',
    navMusic: 'الموسيقى والتوافق',
    navWorkflow: 'كيف يعمل',
    navBlog: 'المدونة',
    navCommunity: 'المجتمع',
    navLogin: 'تسجيل الدخول',
    navGetStarted: 'ابدأ مجاناً',
    snapTitle: 'لقطات فورية (Snaps)',
    snapDesc: 'شارِك صوراً تختفي بعد مشاهدتها. عِش اللحظات الطبيعية بدون تزييف مع حماية الخصوصية.',
    storiesTitle: 'قصص لمدة 24 ساعة',
    storiesDesc: 'عبّر عن يومياتك بالصور والفيديوهات وردّ على القصص مباشرة لبدء المحادثة.',
    musicTitle: 'توافق الموسيقى',
    musicDesc: 'اربط أغانيك المفضلة واستمع إليها مع شريكك أثناء المحادثة لبناء رابط قوي.',
    connectTitle: 'كيف يتواصل شركاء الحياة بسهولة حول العالم',
    connectSub: 'من اكتشاف الذكاء الاصطناعي الذكي إلى الزواج الحقيقي، اكتشف سهولة وأمان المنصة.',
    step1Title: '1. توافق الذكاء الاصطناعي',
    step1Desc: 'يحلل الذكاء الاصطناعي التوافق العميق والقيم لاقتراح أفضل الشركاء.',
    step2Title: '2. اللقطات والقصص والموسيقى',
    step2Desc: 'استكشف لقطاتهم اليومية وقصصهم واختياراتهم الموسيقية لمعرفة شخصيتهم الحقيقية.',
    step3Title: '3. دردشة مباشرة مجانية 100%',
    step3Desc: 'تواصل فوراً بالرسائل والمكالمات الصوتية والمرئية عالية الدقة بدون أي رسوم.',
    step4Title: '4. لقاءات آمنة ورحلة الزواج',
    step4Desc: 'التقِ في فعاليات موثقة وابدأ رحلتك نحو الزواج بأمان وحماية كاملة للهوية.',
  },
  zh: {
    heroDatingPill: '全球交友模式',
    heroMatrimonyPill: '严肃婚恋模式',
    heroTitlePrefix: '连接与聊天',
    heroTitleGradient: '全球 100% 免费。',
    heroSub: '全球首屈一指的 AI 婚恋与交友平台。即时直接聊天，真实认证资料，零强制付费。',
    quickSearchTitle: '快速配对搜索',
    iAmA: '我是',
    lookingFor: '寻找',
    goal: '目标',
    location: '地区',
    findMatchesBtn: '免费寻找匹配',
    trust100Free: '100% 免费直接聊天',
    trustVerified: '真人实名认证',
    trustGlobal: '覆盖全球与海外华人',
    navFeatures: '特色功能',
    navStories: '动态与快照',
    navMusic: '音乐共鸣',
    navWorkflow: '使用流程',
    navBlog: '博客',
    navCommunity: '社区',
    navLogin: '登录',
    navGetStarted: '免费开始使用',
    snapTitle: '即时快照 (Snaps)',
    snapDesc: '分享看完即焚的瞬间照片，展露最真实的自己，具备全方位防截图隐私保护。',
    storiesTitle: '24小时限时动态',
    storiesDesc: '通过图文和短视频展现日常生活，直接回复动态轻松开启自然对话。',
    musicTitle: '音乐品味匹配',
    musicDesc: '同步你的 Spotify 热门单曲，在聊天中一起听歌，用音乐找到心灵契合的另一半。',
    connectTitle: '全球伴侣如何轻松建立连接',
    connectSub: '从 AI 智能推荐到真实走进婚姻，了解我们如何安全快捷地帮你找到终身伴侣。',
    step1Title: '1. AI 智能与星盘契合度',
    step1Desc: 'AI 深度分析性格、价值观及生活习惯，为你精准匹配最契合的对象。',
    step2Title: '2. 快照、动态与音乐互动',
    step2Desc: '查看对方的日常快照、24小时动态及音乐喜好，全方位了解真实性格。',
    step3Title: '3. 100% 免费直接沟通',
    step3Desc: '无需付费即可发送即时消息、语音并开启高清视频通话。',
    step4Title: '4. 安全线下见面与幸福婚姻',
    step4Desc: '参加实名认证的线下活动，在安全有保障的环境中携手步入婚姻殿堂。',
  },
  ja: {
    heroDatingPill: 'ワールドワイドデーティング',
    heroMatrimonyPill: '真剣婚活モード',
    heroTitlePrefix: '繋がる・チャットする',
    heroTitleGradient: '世界中 100% 無料。',
    heroSub: '世界最高峰の AI マッチング＆婚活プラットフォーム。直接チャット、本人確認済み、課金圧力ゼロ。',
    quickSearchTitle: 'クイックパートナー検索',
    iAmA: '性別',
    lookingFor: 'お相手',
    goal: '目的',
    location: '地域',
    findMatchesBtn: '無料でマッチを探す',
    trust100Free: '100% 無料直接チャット',
    trustVerified: '本人確認済みプロフィール',
    trustGlobal: '世界＆海外在住者対応',
    navFeatures: '機能紹介',
    navStories: 'ストーリー＆スナップ',
    navMusic: 'ミュージックマッチ',
    navWorkflow: '使い方',
    navBlog: 'ブログ',
    navCommunity: 'コミュニティ',
    navLogin: 'ログイン',
    navGetStarted: '無料で始める',
    snapTitle: 'インスタントスナップ',
    snapDesc: '閲覧後に消えるスナップ写真で、ありのままの自分をシェア。スクリーンショット防止で安心。',
    storiesTitle: '24時間ストーリー',
    storiesDesc: '日常の様子を写真や動画で投稿。気になるストーリーに直接返信して会話をスタート。',
    musicTitle: '音楽相性マッチング',
    musicDesc: 'お気に入りの曲を連携して、チャット中に一緒に音楽を聴きながら絆を深めましょう。',
    connectTitle: '運命のパートナーと繋がる仕組み',
    connectSub: 'AI によるスマートマッチから本物の結婚まで、安全かつスムーズに理想の相手と繋がります。',
    step1Title: '1. AI スマート＆相性診断',
    step1Desc: 'AI が価値観や条件を詳細に分析し、あなたに最適なパートナーを厳選提案。',
    step2Title: '2. スナップ・ストーリー・音楽',
    step2Desc: '日常の投稿や音楽の好みを通して、相手のリアルな人柄を自然に知ることができます。',
    step3Title: '3. 100% 無料ダイレクトチャット',
    step3Desc: '追加料金なしでメッセージ、ボイスメッセージ、HD ビデオ通話を自由に利用可能。',
    step4Title: '4. 安全な対面と結婚への道のり',
    step4Desc: '認証済みのイベントや個別の対面で安心して会い、素敵な結婚生活をスタート。',
  },
  ko: {
    heroDatingPill: '글로벌 데이팅 모드',
    heroMatrimonyPill: '진지한 결혼·매칭 모드',
    heroTitlePrefix: '전 세계 싱글과',
    heroTitleGradient: '100% 무료 연결 & 대화.',
    heroSub: '세계 1위 AI 기반 글로벌 데이팅 및 결혼 매칭 플랫폼. 강제 유료 결제 없는 즉시 다이렉트 채팅, 철저한 본인 인증 프로필.',
    quickSearchTitle: '빠른 이상형 검색',
    iAmA: '본인 성별',
    lookingFor: '희망 상대',
    goal: '목적',
    location: '지역',
    findMatchesBtn: '무료로 매칭 찾기',
    trust100Free: '100% 무료 다이렉트 채팅',
    trustVerified: '인증된 실제 회원 프로필',
    trustGlobal: '한국 & 글로벌 네트워크',
    navFeatures: '기능 소개',
    navStories: '스토리 & 스냅',
    navMusic: '뮤직 매칭',
    navWorkflow: '이용 방법',
    navBlog: '블로그',
    navCommunity: '커뮤니티',
    navLogin: '로그인',
    navGetStarted: '무료로 시작하기',
    snapTitle: '순간 스냅 (Snaps)',
    snapDesc: '확인 후 사라지는 일상 사진으로 솔직한 매력을 공유하세요. 필터 부담 없는 자연스러움과 화면 캡처 방지 기능.',
    storiesTitle: '24시간 일상 스토리',
    storiesDesc: '사진과 동영상으로 일상을 공유하고, 마음에 드는 스토리에 답장하여 자연스럽게 대화를 시작해보세요.',
    musicTitle: '음악 취향 매칭',
    musicDesc: '스포티파이 최애곡을 연동하여 실시간 채팅 중 함께 음악을 들으며 감성을 나눠보세요.',
    connectTitle: '인연을 맺는 4단계 프로세스',
    connectSub: '스마트한 AI 매칭부터 진지한 만남과 결혼까지, 안전하고 편리하게 이상형을 찾아드립니다.',
    step1Title: '1. AI 스마트 궁합 분석',
    step1Desc: '가치관, 라이프스타일, 연애관을 AI가 정밀 분석하여 최적의 매칭 상대를 추천합니다.',
    step2Title: '2. 일상 스냅과 음악으로 교감',
    step2Desc: '스냅 사진과 24시간 스토리, 음악 취향을 통해 상대방의 진짜 분위기를 확인하세요.',
    step3Title: '3. 100% 무료 다이렉트 대화',
    step3Desc: '결제 유도 없이 텍스트 메시지, 음성 메시지, 고화질 HD 영상통화까지 자유롭게 이용하세요.',
    step4Title: '4. 안전한 오프라인 만남과 결혼',
    step4Desc: '신원 확인을 거친 안전한 만남으로 평생을 함께할 소중한 인연을 만들어보세요.',
  },
  pt: {
    heroDatingPill: 'Modo Namoro Mundial',
    heroMatrimonyPill: 'Modo Casamento Sério',
    heroTitlePrefix: 'Conecte-se e Converse',
    heroTitleGradient: 'Grátis no mundo todo.',
    heroSub: 'A plataforma de IA nº 1 do mundo para namoro internacional e casamento sério. Chat direto instantâneo, perfis verificados e sem assinaturas forçadas.',
    quickSearchTitle: 'Busca Rápida de Par ideal',
    iAmA: 'Eu sou',
    lookingFor: 'Procuro',
    goal: 'Objetivo',
    location: 'Localização',
    findMatchesBtn: 'Buscar Combinações Grátis',
    trust100Free: 'Chat Direto 100% Grátis',
    trustVerified: 'Perfis Humanos Verificados',
    trustGlobal: 'Alcance Global e NRI',
    navFeatures: 'Recursos',
    navStories: 'Histórias e Snaps',
    navMusic: 'Vibe Musical',
    navWorkflow: 'Como Funciona',
    navBlog: 'Blog',
    navCommunity: 'Comunidade',
    navLogin: 'Entrar',
    navGetStarted: 'Começar Grátis',
    snapTitle: 'Snaps Instantâneos',
    snapDesc: 'Compartilhe momentos fotográficos que desaparecem após a visualização. Momentos autênticos sem pressão.',
    storiesTitle: 'Feed de Stories de 24 Horas',
    storiesDesc: 'Expresse seu dia a dia com fotos e vídeos. Responda diretamente a qualquer história para iniciar conversas.',
    musicTitle: 'Combinação por Música',
    musicDesc: 'Sincronize suas músicas favoritas do Spotify e ouça junto no chat ao vivo.',
    connectTitle: 'Como os Parceiros de Vida se Conectam',
    connectSub: 'Da busca com IA inteligente até o casamento real, conectamos você ao seu par com facilidade e segurança.',
    step1Title: '1. Combinação IA e Cósmica',
    step1Desc: 'Nossa IA analisa compatibilidade profunda, valores e preferências para sugerir os melhores pares.',
    step2Title: '2. Snaps, Stories e Música',
    step2Desc: 'Explore snaps diários, histórias de 24h e gostos musicais para conhecer a verdadeira personalidade.',
    step3Title: '3. Chat Direto 100% Grátis',
    step3Desc: 'Converse, envie áudios e faça chamadas de vídeo HD sem custos ou assinaturas ocultas.',
    step4Title: '4. Encontros Seguros e Casamento',
    step4Desc: 'Encontre-se em eventos locais verificados e inicie sua jornada para o casamento com segurança total.',
  },
  th: {
    heroDatingPill: 'โหมดหาแฟนทั่วโลก',
    heroMatrimonyPill: 'โหมดหาคู่แต่งงานจริงจัง',
    heroTitlePrefix: 'เชื่อมต่อและแชท',
    heroTitleGradient: 'ฟรีทั่วโลก',
    heroSub: 'แพลตฟอร์ม AI อันดับ 1 ของโลกสำหรับการหาคู่และหาคู่แต่งงาน แชทตรงทันที โปรไฟล์จริง ยืนยัน OTP ฟรี 100%',
    quickSearchTitle: 'ค้นหาคู่แมตช์ด่วน',
    iAmA: 'ฉันคือ',
    lookingFor: 'มองหา',
    goal: 'เป้าหมาย',
    location: 'สถานที่',
    findMatchesBtn: 'ค้นหาคู่แมตช์ฟรี',
    trust100Free: 'แชทตรงฟรี 100%',
    trustVerified: 'โปรไฟล์ยืนยันตัวตนจริง',
    trustGlobal: 'ค้นหาได้ทั่วโลก',
    navFeatures: 'ฟีเจอร์',
    navStories: 'สตอรี่และสแนป',
    navMusic: 'แมตช์ด้วยเพลง',
    navWorkflow: 'วิธีการทำงาน',
    navBlog: 'บล็อก',
    navCommunity: 'ชุมชน',
    navLogin: 'เข้าสู่ระบบ',
    navGetStarted: 'เริ่มต้นใช้งานฟรี',
    snapTitle: 'สแนปรูปภาพทันใจ',
    snapDesc: 'แชร์รูปภาพที่ดูได้ครั้งเดียวแล้วหายไป ไร้ความกังวล พร้อมระบบป้องกันสกรีนช็อต',
    storiesTitle: 'สตอรี่ 24 ชั่วโมง',
    storiesDesc: 'แบ่งปันช่วงเวลาในชีวิตผ่านสตอรี่รูปภาพและวิดีโอ ตอบกลับสตอรี่เพื่อเริ่มคุยได้ทันที',
    musicTitle: 'แมตช์สไตล์ดนตรี',
    musicDesc: 'ซิงค์เพลงโปรดจาก Spotify และฟังเพลงร่วมกันในห้องแชทสด',
    connectTitle: 'การเริ่มต้นคู่ชีวิตใน LifePartner AI',
    connectSub: 'จากการวิเคราะห์ของ AI สู่การแต่งงานที่แท้จริง ปลอดภัยและสบายใจ',
    step1Title: '1. แมตช์ด้วย AI อัจฉริยะ',
    step1Desc: 'ระบบ AI วิเคราะห์ความเข้ากันและค่านิยมเพื่อแนะนำคนที่ใช่ที่สุด',
    step2Title: '2. สแนป สตอรี่ และดนตรี',
    step2Desc: 'รู้จักตัวตนที่แท้จริงผ่านไลฟ์สไตล์ เพลง และสตอรี่ประจำวัน',
    step3Title: '3. แชทตรงฟรี 100%',
    step3Desc: 'ส่งข้อความและวิดีโอคอล HD ฟรี ไม่มีค่าธรรมเนียมแอบแฝง',
    step4Title: '4. ปลอดภัยไร้กังวล',
    step4Desc: 'ระบบ Anti-Creep Shield ช่วยดูแลความปลอดภัยของผู้หญิงตลอดการใช้งาน'
  },
  ms: {
    heroDatingPill: 'Mod Temujanji Global',
    heroMatrimonyPill: 'Mod Perkahwinan Serius',
    heroTitlePrefix: 'Berhubung & Berbual',
    heroTitleGradient: 'Percuma Seluruh Dunia.',
    heroSub: 'Platform AI #1 dunia untuk temujanji selamat & perkahwinan serius. Sembang terus percuma, profil disahkan OTP, tiada caj paksa.',
    quickSearchTitle: 'Carian Pantas',
    iAmA: 'Saya seorang',
    lookingFor: 'Mencari',
    goal: 'Tujuan',
    location: 'Lokasi',
    findMatchesBtn: 'Cari Pasangan Percuma',
    trust100Free: 'Sembang Terus 100% Percuma',
    trustVerified: 'Profil Manusia Disahkan OTP',
    trustGlobal: 'Jangkauan Global & Tempatan',
    navFeatures: 'Ciri-Ciri',
    navStories: 'Stories & Snaps',
    navMusic: 'Padanan Muzik',
    navWorkflow: 'Cara Berfungsi',
    navBlog: 'Blog',
    navCommunity: 'Komuniti',
    navLogin: 'Log Masuk',
    navGetStarted: 'Mula Percuma',
    snapTitle: 'Snap Gambar Segera',
    snapDesc: 'Kongsi foto yang hilang selepas dilihat dengan perlindungan tangkapan skrin.',
    storiesTitle: 'Suapan Stories 24 Jam',
    storiesDesc: 'Kongsi detik harian melalui gambar dan video untuk perbualan semulajadi.',
    musicTitle: 'Padanan Jiwa Muzik',
    musicDesc: 'Segerakkan lagu Spotify kegemaran dan dengar bersama dalam sembang.',
    connectTitle: 'Bagaimana Pasangan Bertemu di LifePartner AI',
    connectSub: 'Dari padanan AI sehingga ke jinjang pelamin dengan selamat.',
    step1Title: '1. Padanan AI Beretika',
    step1Desc: 'AI menganalisis keserasian nilai hidup dan prinsip perkahwinan.',
    step2Title: '2. Stories, Muzik & Gaya Hidup',
    step2Desc: 'Kenali personaliti sebenar melalui perkongsian harian.',
    step3Title: '3. 100% Percuma untuk Wanita',
    step3Desc: 'Queen VIP seumur hidup dengan mesej tanpa had dan panggilan video.',
    step4Title: '4. Privasi & Keselamatan',
    step4Desc: 'Perisai Anti-Creep melindungi nombor peribadi anda pada setiap masa.'
  },
  id: {
    heroDatingPill: 'Mode Kencan Global',
    heroMatrimonyPill: 'Mode Pernikahan & Taaruf Serius',
    heroTitlePrefix: 'Terhubung & Mengobrol',
    heroTitleGradient: 'Gratis Seluruh Dunia.',
    heroSub: 'Platform AI #1 dunia untuk kencan aman & taaruf pernikahan serius. Chat langsung gratis, profil terverifikasi OTP, bebas langganan paksa.',
    quickSearchTitle: 'Pencarian Cepat',
    iAmA: 'Saya seorang',
    lookingFor: 'Mencari',
    goal: 'Tujuan',
    location: 'Lokasi',
    findMatchesBtn: 'Cari Pasangan Gratis',
    trust100Free: 'Chat Langsung 100% Gratis',
    trustVerified: 'Profil Manusia Terverifikasi OTP',
    trustGlobal: 'Jangkauan Seluruh Indonesia & Global',
    navFeatures: 'Fitur',
    navStories: 'Stories & Snaps',
    navMusic: 'Kecocokan Musik',
    navWorkflow: 'Cara Kerja',
    navBlog: 'Blog',
    navCommunity: 'Komunitas',
    navLogin: 'Masuk',
    navGetStarted: 'Mulai Gratis',
    snapTitle: 'Snap Foto Sekali Lihat',
    snapDesc: 'Bagikan foto yang otomatis terhapus setelah dilihat dengan proteksi tangkapan layar.',
    storiesTitle: 'Feed Cerita 24 Jam',
    storiesDesc: 'Ekspresikan hari-hari Anda melalui foto dan video untuk obrolan santai dan natural.',
    musicTitle: 'Kecocokan Selera Musik',
    musicDesc: 'Sinkronkan lagu favorit Spotify dan dengarkan bersama saat mengobrol.',
    connectTitle: 'Cara Calon Pasangan Bertemu',
    connectSub: 'Dari rekomendasi AI cerdas hingga ke jenjang pernikahan yang bahagia.',
    step1Title: '1. Analisis AI Mendalam',
    step1Desc: 'Kecerdasan buatan menyaring nilai, prinsip hidup, dan kriteria pasangan idaman.',
    step2Title: '2. Cerita, Musik & Kepribadian',
    step2Desc: 'Pahami calon pasangan lebih dekat lewat rutinitas harian dan minat musik.',
    step3Title: '3. 100% Gratis untuk Wanita',
    step3Desc: 'Akses Queen VIP seumur hidup dengan bebas kirim pesan dan panggilan video.',
    step4Title: '4. Aman Terlindungi',
    step4Desc: 'AI Anti-Creep melindungi privasi dan nomor WhatsApp Anda dari gangguan.'
  },
  ru: {
    heroDatingPill: 'Международные знакомства',
    heroMatrimonyPill: 'Серьезные отношения и брак',
    heroTitlePrefix: 'Общайтесь и знакомьтесь',
    heroTitleGradient: 'Бесплатно по всему миру.',
    heroSub: 'Платформа #1 на базе AI для серьезных знакомств и создания семьи. Прямой чат, подтвержденные анкеты через OTP, без скрытых подписок.',
    quickSearchTitle: 'Быстрый поиск пары',
    iAmA: 'Я',
    lookingFor: 'Ищу',
    goal: 'Цель',
    location: 'Город',
    findMatchesBtn: 'Найти пару бесплатно',
    trust100Free: '100% Бесплатный прямой чат',
    trustVerified: 'Проверенные анкеты людей',
    trustGlobal: 'По всей России и миру',
    navFeatures: 'Возможности',
    navStories: 'Истории и Снапы',
    navMusic: 'Музыкальный вкус',
    navWorkflow: 'Как это работает',
    navBlog: 'Блог',
    navCommunity: 'Сообщество',
    navLogin: 'Войти',
    navGetStarted: 'Начать бесплатно',
    snapTitle: 'Исчезающие снапы',
    snapDesc: 'Делитесь фотоснимками, которые исчезают после просмотра, с защитой от сохранения экрана.',
    storiesTitle: '24-часовые истории',
    storiesDesc: 'Показывайте свою жизнь через фото и видео. Отвечайте на истории, чтобы начать разговор.',
    musicTitle: 'Совпадение по музыке',
    musicDesc: 'Синхронизируйте любимые треки из Spotify и слушайте музыку вместе в чате.',
    connectTitle: 'Как создаются пары в LifePartner AI',
    connectSub: 'От интеллектуального подбора на базе AI до настоящей счастливой семьи.',
    step1Title: '1. AI-анализ совместимости',
    step1Desc: 'AI оценивает ценности, взгляды на жизнь и цели для точного подбора.',
    step2Title: '2. Истории, снапы и музыка',
    step2Desc: 'Узнавайте настоящего человека через его повседневную жизнь и любимую музыку.',
    step3Title: '3. Бесплатный Queen VIP для женщин',
    step3Desc: 'Безлимитные сообщения, HD-видеозвонки и монеты для подарков без оплат.',
    step4Title: '4. Полная безопасность',
    step4Desc: 'AI Anti-Creep Shield блокирует грубость и защищает номер телефона.'
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
  currentLangObj: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    // 1. Check URL query parameter ?lang=...
    if (typeof window !== 'undefined') {
      const urlParams = new URLSearchParams(window.location.search);
      const langParam = urlParams.get('lang') as LanguageCode;
      if (langParam && TRANSLATIONS[langParam]) {
        setLanguageState(langParam);
        localStorage.setItem('lp_lang', langParam);
        document.documentElement.lang = langParam;
        const langObj = SUPPORTED_LANGUAGES.find(l => l.code === langParam);
        document.documentElement.dir = langObj?.dir || 'ltr';
        return;
      }
    }

    // 2. Check localStorage
    const saved = localStorage.getItem('lp_lang') as LanguageCode;
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved);
      document.documentElement.lang = saved;
      const langObj = SUPPORTED_LANGUAGES.find(l => l.code === saved);
      document.documentElement.dir = langObj?.dir || 'ltr';
    } else if (typeof navigator !== 'undefined') {
      const browserLang = navigator.language.slice(0, 2).toLowerCase();
      if (TRANSLATIONS[browserLang as LanguageCode]) {
        setLanguageState(browserLang as LanguageCode);
      }
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('lp_lang', lang);
      document.documentElement.lang = lang;
      const langObj = SUPPORTED_LANGUAGES.find(l => l.code === lang);
      document.documentElement.dir = langObj?.dir || 'ltr';
    }
  };

  const currentLangObj = SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[0];

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: currentLangObj.dir || 'ltr', currentLangObj }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback if rendered outside provider
    return {
      language: 'en' as LanguageCode,
      setLanguage: () => {},
      t: (key: string) => TRANSLATIONS.en[key] || key,
      dir: 'ltr' as const,
      currentLangObj: SUPPORTED_LANGUAGES[0]
    };
  }
  return context;
};
